// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm0ZqPNKjvIS_zEhDclQWwwSSEy0FDXlo',
    appId: '1:562460191316:web:7bdb675690afeccaaa5bc1',
    messagingSenderId: '562460191316',
    projectId: 'flutter-app-lap',
    authDomain: 'flutter-app-lap.firebaseapp.com',
    storageBucket: 'flutter-app-lap.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSf-tZKANl-tPyanRW4V3_6HQWjGRRYkQ',
    appId: '1:562460191316:android:44d92d31c903ad89aa5bc1',
    messagingSenderId: '562460191316',
    projectId: 'flutter-app-lap',
    storageBucket: 'flutter-app-lap.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqOhiZgbo6LUo8YFb2hWHDRnHYtKnzUis',
    appId: '1:562460191316:ios:bdd91f590ee5deecaa5bc1',
    messagingSenderId: '562460191316',
    projectId: 'flutter-app-lap',
    storageBucket: 'flutter-app-lap.appspot.com',
    iosClientId: '562460191316-v6g43agdc8g4ajuqrvsq28fvvna59kuu.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqOhiZgbo6LUo8YFb2hWHDRnHYtKnzUis',
    appId: '1:562460191316:ios:bdd91f590ee5deecaa5bc1',
    messagingSenderId: '562460191316',
    projectId: 'flutter-app-lap',
    storageBucket: 'flutter-app-lap.appspot.com',
    iosClientId: '562460191316-v6g43agdc8g4ajuqrvsq28fvvna59kuu.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterapp',
  );
}
